spring:
  application:
    name: TongyiZuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

zuul:
  routes:
    user:
      path: /user/**
      serviceId: userApi
    msg:
      path: /msg/**
      serviceId: msgApi


